// src/routes/01/+page.svelte
<script lang="ts" >
  import { onMount } from 'svelte';
  import * as T from 'three'

  onMount(()=>{

    const canvas = document.getElementById("canvas-t") as HTMLElement
    const scene = new T.Scene()
    const size = {w: window.innerWidth, h: window.innerHeight, ratio:window.innerWidth/window.innerHeight}
    const cam = new T.PerspectiveCamera(74, size.ratio)
    cam.position.z = 3
    cam.position.x = 1
    cam.position.y = 1
    scene.add(cam)

    const cubeGeo = new T.BoxGeometry(1,1,1)
    const cubeMat = new T.MeshBasicMaterial({color:'red'})
    const cube = new T.Mesh(cubeGeo, cubeMat)
    scene.add(cube)

    cube.position.y = 1
    cube.scale.y = 2.2


    const axesHelper = new T.AxesHelper(4)
    scene.add(axesHelper)

    cam.lookAt(cube.position)


    const renderer = new T.WebGLRenderer({canvas})
    renderer.setSize(size.w, size.h)

    renderer.render(scene,cam )
  })


</script>

<main class="min-w-screen min-h-screen">
  <div class=" text-white p-2 absolute top-0 right-0 bg-[#1a1a1a] border-l border-b">04</div>
  <canvas class="min-w-screen min-h-screen" id="canvas-t" ></canvas>
</main>

// src/pages/01/index.tsx
"use client";

import { useEffect, useRef } from "react";
import * as THREE from "three";

export default function ThreeDemo() {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    if (!canvasRef.current) return;

    // Cena
    const scene = new THREE.Scene();

    // Cubo
    const geometry = new THREE.BoxGeometry(1, 1, 1);
    const material = new THREE.MeshBasicMaterial({
      color: "#f00",
    });
    const cube = new THREE.Mesh(geometry, material);
    scene.add(cube);

    // Tamanho
    const sizes = {
      width: window.innerWidth,
      height: window.innerHeight,
    };

    // Camera
    const camera = new THREE.PerspectiveCamera(
      75,
      sizes.width / sizes.height,
      0.1,
      1000,
    );
    camera.position.z = 3;
    scene.add(camera);

    // Renderer
    const renderer = new THREE.WebGLRenderer({ canvas: canvasRef.current });
    renderer.setSize(sizes.width, sizes.height);

    // Loop de animação
    const animate = () => {
      requestAnimationFrame(animate);
      cube.rotation.x += 0.01;
      cube.rotation.y += 0.01;
      renderer.render(scene, camera);
    };
    animate();

    // Resize handler
    const handleResize = () => {
      sizes.width = window.innerWidth;
      sizes.height = window.innerHeight;
      camera.aspect = sizes.width / sizes.height;
      camera.updateProjectionMatrix();
      renderer.setSize(sizes.width, sizes.height);
    };
    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
      renderer.dispose();
    };
  }, []);

  return <canvas ref={canvasRef} id="canvas" />;
}
